### ISSUE TITLE
Terminfindung

### ISSUE THREAD

**Issue by mfa** [shackspace/IT-Toshokan#2]
Vorschlag: Mitte Oktober erstes Treffen?

**Comment by michael-k** [comment]
+1

**Comment by mfa** [comment]
https://dudle.inf.tu-dresden.de/privacy/erstes_Treffen_des_IT-Toshokan/

**Comment by bronsen** [comment]
@mfa und @bronsen beschließen: 

Mittwoch **11.11.2015** ist erstes Treffen.

**Comment by michael-k** [comment]
:+1:
